"""Initial schema

Revision ID: 25ad109fac85
Revises: 
Create Date: 2023-11-07 12:08:36.419441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25ad109fac85'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wio', sa.String(length=45), nullable=False),
    sa.Column('macaddress', sa.String(length=45), nullable=True),
    sa.Column('code', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('macaddress')
    )
    op.create_table('wiodata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('type', sa.String(length=45), nullable=False),
    sa.Column('id_wio', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_wio'], ['wio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wiodata')
    op.drop_table('wio')
    # ### end Alembic commands ###
